### ISSUE TITLE
"error: no such subcommand: `+nightly-2022-09-07`" when using rustdoc-json on windows

### ISSUE THREAD

**Issue by jnises** [cargo-public-api/cargo-public-api#143] opened 2022-09-13 07:37 UTC
It seems I'm running into this bug https://github.com/rust-lang/rustup/issues/3036
Nested cargo invocations have issues in recent versions of rustup on windows.

I'm trying to run code like:
```rust
rustdoc_json::build(BuildOptions::default().toolchain("+nightly"))
```

I'm on Windows 11

I can work around the issue by making `cargo_rustdoc_command` call `rustup run nightly-2022-09-07 cargo ...` instead of `cargo +nightly-2022-09-07 ...`

What is the correct way to run nested a cargo with a different toolchain?

**Comment by Enselic** [comment] 2022-09-14 18:31
Thanks for reporting!

@Emilgardis Do you see any problem with us using `rustup run ...` instead?

@jnises Any chance you can create a PR with what works for you? If all our existing regression tests pass after the change, I am comfortable to use the change, because we have a good set of regression tests. 

Assuming @Emilgardis does not know of any issues with switching to that. But I do believe that is also what cargo-expand is using, probably for good reason.

**Comment by Emilgardis** [comment] 2022-09-14 18:46
switching to `rustup run <toolchain> cargo ...` when an override is mentioned sounds good, that's what +toolchain is supposed to be semantically equivalent to

Basically https://github.com/Enselic/cargo-public-api/blob/e40061548e90a96c639a7506939b74965677abc2/rustdoc-json/src/build.rs#L50-L56

would become

```rust
    let mut command = if let Some(toolchain) = OVERRIDDEN_TOOLCHAIN.or(requested_toolchain.as_deref()) {
        Command::new("rustup").args(["run", toolchain, "cargo"])
    } else {
        Command::new("cargo")
    }

    command.arg("rustdoc");    
```

**Comment by jnises** [comment] 2022-09-15 06:19
https://github.com/Enselic/cargo-public-api/pull/147 seems to do the same thing as my workaround.
So that should fix my issue :)

**Comment by Enselic** [comment] 2022-09-18 12:08
Closed by https://github.com/Enselic/cargo-public-api/pull/147

**Closed as completed by Enselic** 2022-09-18 12:08 UTC
Labels: bug, windows
